apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: budget-tracker
  labels:
    app: {{ .Release.Name }}
    version: v1
data:
  REACT_APP_API_URL: http://budget-tracker-backend-service