apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: budget-tracker
  labels:
    app: {{ .Release.Name }}
    version: v1
data:
  REACT_APP_BACKEND_HOST: http://budget-tracker-backend-service.budget-tracker.svc.cluster.local