version: "3.7"

services:
  budget-tracker-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.Dev
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
  budget-tracker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.Dev
    ports:
      - 5000:80
    environment:
      - "ConnectionStrings__DefaultConnection=Server=mssql;Database=BudgetTracker;User Id=sa;Password=1StrongPwd!!"
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1StrongPwd!!
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
