version: "3.7"

services:
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1StrongPwd!!
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
  budget-tracker-backend:
    depends_on:
      - mssql
    build:
      context: ./backend
      dockerfile: Dockerfile.Dev
    ports:
      - 5002:80
      - 5001:443
    environment:
      - "ConnectionStrings__DefaultConnection=Server=mssql;Database=BudgetTracker;User Id=sa;Password=1StrongPwd!!"
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_HTTPS_PORT=5001"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "${HOME}/.aspnet:/https/"
  budget-tracker-frontend:
    depends_on:
      - budget-tracker-backend
    build:
      context: ./client
      dockerfile: Dockerfile.Dev
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_HOST=https://localhost:5001
