apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: budget-tracker
  labels:
    app: {{ .Release.Name }}
data:
  ConnectionStrings__DefaultConnection: {{ .Values.Config.connectionString }}