apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http-port
      protocol: {{ .Values.port.protocol }}
      port: {{ .Values.port.value }}
      targetPort: {{ .Values.port.target }}
  type: ClusterIP
