apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-volume
  labels:
    app: mssql
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
